language: node_js
dist: bionic
branches:
  only:
    - master

node_js:
  - '12'
  - '13'
  - '14'

install: yarn --frozen-lockfile

script:
  - yarn codegen
  - yarn build
  - yarn test
  - yarn typecheck
  - yarn lint

deploy:
  skip_cleanup: true
  provider: script
  script: >-
    yarn config set _authToken $NPM_AUTH_TOKEN &&
    yarn version --cwd dist --non-interactive --no-git-tag-version --new-version=$(jq -r .version package.json)-dev.${TRAVIS_COMMIT::8} &&
    yarn publish --cwd dist --non-interactive --tag=dev
  on:
    branch: develop
    condition: $TRAVIS_NODE_VERSION = 14

notifications:
  email:
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules
